---
- name: install vagrant
  homebrew_cask: name=vagrant state=present

- name: install vagrant completion
  homebrew: name=vagrant-completion state=latest

- name: check that vagrant plugins exist
  shell: vagrant plugin list | fgrep {{ item }}
  changed_when: false
  ignore_errors: yes
  failed_when: no
  with_items: "{{ vagrant_plugins }}"
  register: vagrant_plugins_check

- name: vagrant plugins
  command: vagrant plugin install {{ vagrant_plugins_check.results[item.0].item }}
  when: vagrant_plugins_check.results[item.0].rc != 0
  with_indexed_items: "{{ vagrant_plugins }}"
