---
# Homebrew Unix Software
- name: update homebrew to the latest version
  homebrew: update_homebrew=yes

- name: brew packages
  homebrew: name={{ item }} state=latest
  ignore_errors: true
  with_items: "{{ brew_packages }}"

- name: Mac Apple Store | Install apps.
  shell: mas list | grep "{{ item.id }}" || mas install "{{ item.id }}"
  with_items: "{{ appstore_apps }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1

- name: Mac Apple Store | Upgrade apps.
  shell: mas list | grep "{{ item.id }}" || mas upgrade "{{ item.id }}"
  with_items: "{{ appstore_apps }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1
