---
- name: Upgrade Atom packages if configured.
  atom:
    upgrade_all: yes
  when: atom_upgrade_all
  environment:
    PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"

- name: Ensure configured Atom packages are installed.
  atom:
    name: "{{ item }}"
    state: present
  with_items: "{{ atom_packages }}"
  environment:
    PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"
