---
brew_packages:
  # Unix Utilities
  - cask
  - bash
  - ctags
  - curl
  - dockutil
  - findutils
  - fish
  - git
  - gnu-sed
  - hugo
  - iperf3
  - md5sha1sum
  - rlwrap
  - mas              # utility for appstore cli
  - nmap
  - sassc
  - shellcheck
  - tree
  - watch
  - wget
  - wireshark
  - xz
  - utm
  - bash-completion
  - atom
  - appcleaner
  - bestres
  - bootchamp
  - cog
  - discord
  - dropbox
  - evernote
  - firefox
  - notion
  - flux
  - google-chrome
  - iterm2
  - macdown
  - mplayerx
  - pl2303                 # usb to serial driver for mac os
  - skype
  - slack
  - spotify
  - virtualbox
  - zoom

  # Commercial
  - dash
  - entropy
  - textual

appstore_apps:
  - name: Magnet
    id: 441258766
  - name: Apple Remote Desktop
    id: 409907375
  - name: Forecast Bar
    id: 982710545
  - name: Boom 2
    id: 948176063
  - name: Microsoft Remote Desktop
    id: 715768417
